name: Deploy Fake
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: 'development'
jobs:
  deploy-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy in the environment
        run: echo "Deploying to the environment ${{ inputs.environment }}"