name: CI/CD Fake
on:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        run: echo "Execution of docker build command"
      - name: Run Software Tests
        run: echo "Execution of software tests"
      - name: Publish Release
        run: echo "Execution of release publishing"
  CD:
    needs: [ CI ]
    uses: victormilk/workflow-reuse/.github/workflows/cd.yml@main
    secrets:
      environment: ${{ secrets.ENVIRONMENT_DEPLOY }}